version: "2"
services:
    mysql:
        image: mysql:8.2.0
        container_name: mysql-server
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: 1234
        ports:
            - "3306:3306"
        volumes:
            - "./mnt:/docker-entrypoint-initdb.d"
